import { useEffect, useState, FormEvent } from "react";
import { Link } from "react-router-dom";
import { supabase } from "../lib/supabase";
import { apiPost } from "../lib/api";
import { useAuth } from "../contexts/AuthContext";

interface Project {
  id: string;
  name: string;
  status: string;
  created_at: string;
}

interface Standard {
  code: string;
  name: string;
}

const STATUS_LABELS: Record<string, string> = {
  en_cours: "En cours",
  audit: "Audit",
  correction: "Correction",
  finalise: "Finalisé",
};

interface GenerateStandardResult {
  existing: boolean;
  code: string;
  name: string;
  clausesCount?: number;
  documentsCount?: number;
  autoGenerated?: boolean;
}

export default function DashboardPage() {
  const { isPlatformAdmin } = useAuth();
  const [projects, setProjects] = useState<Project[]>([]);
  const [standards, setStandards] = useState<Standard[]>([]);
  const [showForm, setShowForm] = useState(false);
  const [name, setName] = useState("");
  const [standardCode, setStandardCode] = useState("");
  const [error, setError] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);
  const [normQuery, setNormQuery] = useState("");
  const [generating, setGenerating] = useState(false);
  const [generatingStep, setGeneratingStep] = useState<string | null>(null);
  const [generateNotice, setGenerateNotice] = useState<string | null>(null);

  async function loadData() {
    const [{ data: projectsData }, { data: standardsData }] = await Promise.all([
      supabase.from("projects").select("id, name, status, created_at").order("created_at", { ascending: false }),
      supabase.from("standards").select("code, name").eq("is_active", true),
    ]);
    setProjects(projectsData ?? []);
    setStandards(standardsData ?? []);
    if (standardsData?.length && !standardCode) setStandardCode(standardsData[0].code);
  }

  useEffect(() => {
    void loadData();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  // Étape rejouable : les endpoints sont idempotents, on retente après une
  // coupure réseau (le proxy peut couper les réponses longues sans tuer le serveur).
  async function retryStep<T>(call: () => Promise<T>, attempts = 3): Promise<T> {
    let lastError: unknown;
    for (let i = 0; i < attempts; i++) {
      try {
        return await call();
      } catch (err) {
        lastError = err;
        const message = err instanceof Error ? err.message : "";
        // Erreur métier renvoyée par l'API (4xx/5xx avec message) : inutile de retenter
        if (message && !/failed to fetch|networkerror|load failed|erreur 50[24]/i.test(message)) {
          throw err;
        }
        await new Promise((r) => setTimeout(r, 5000 * (i + 1)));
      }
    }
    throw lastError;
  }

  async function pollRequestResult(requestId: string): Promise<GenerateStandardResult> {
    const deadline = Date.now() + 10 * 60 * 1000;
    while (Date.now() < deadline) {
      await new Promise((r) => setTimeout(r, 10000));
      const { data: request } = await supabase
        .from("standard_requests")
        .select("status, error_message, standards(code, name)")
        .eq("id", requestId)
        .maybeSingle();
      if (request?.status === "traitee" && request.standards) {
        const std = request.standards as unknown as { code: string; name: string };
        return { existing: false, code: std.code, name: std.name };
      }
      if (request?.status === "erreur") {
        throw new Error(request.error_message || "La préparation a échoué");
      }
    }
    throw new Error(
      "La préparation prend plus de temps que prévu. Rechargez la page dans quelques minutes : la norme apparaîtra dans la liste."
    );
  }

  async function handleGenerateStandard() {
    const query = normQuery.trim();
    if (!query || generating) return;
    setGenerating(true);
    setError(null);
    setGenerateNotice(null);

    try {
      // Étape 1 : identification (rapide)
      setGeneratingStep("Identification de la norme…");
      const identity = await apiPost<GenerateStandardResult & { requestId?: string }>(
        "/api/standards/generate",
        { query }
      );

      let result: GenerateStandardResult;
      if (identity.existing || !identity.requestId) {
        result = identity;
      } else {
        const requestId = identity.requestId;
        // Étape 2 : recherche web approfondie
        setGeneratingStep(`Recherche approfondie sur ${identity.name}… (2 à 4 min)`);
        await retryStep(() => apiPost("/api/standards/research", { requestId }));

        // Étape 3 : construction du référentiel
        setGeneratingStep("Construction du référentiel (clauses, documents, schémas)… (3 à 7 min)");
        try {
          result = await retryStep(
            () => apiPost<GenerateStandardResult>("/api/standards/build", { requestId }),
            2
          );
        } catch {
          // Le serveur a pu terminer malgré la coupure : on suit l'état en base
          setGeneratingStep("Finalisation…");
          result = await pollRequestResult(requestId);
        }
      }

      await loadData();
      setStandardCode(result.code);
      setNormQuery("");
      setGenerateNotice(
        result.existing
          ? `${result.name} est déjà au catalogue — elle est sélectionnée ci-dessus.`
          : `${result.name} est prête` +
            (result.clausesCount
              ? ` (${result.clausesCount} clauses, ${result.documentsCount} documents requis)`
              : "") +
            `. Ce référentiel a été préparé automatiquement par l'IA ; un expert le relira prochainement. ` +
            `Vous pouvez dès maintenant créer votre projet.`
      );
    } catch (err) {
      setError(err instanceof Error ? err.message : "La préparation de la norme a échoué");
    } finally {
      setGenerating(false);
      setGeneratingStep(null);
    }
  }

  async function handleCreate(e: FormEvent) {
    e.preventDefault();
    setError(null);
    setLoading(true);
    try {
      await apiPost("/api/projects/create", { name, standardCode });
      setName("");
      setShowForm(false);
      await loadData();
    } catch (err) {
      setError(err instanceof Error ? err.message : "Une erreur est survenue");
    } finally {
      setLoading(false);
    }
  }

  return (
    <div className="page">
      <header className="page-header">
        <h1>Vos projets de certification</h1>
        <div className="header-actions">
          {isPlatformAdmin && (
            <Link to="/admin" className="back-link">
              Administration
            </Link>
          )}
          <button onClick={() => setShowForm(!showForm)}>
            {showForm ? "Annuler" : "Nouveau projet"}
          </button>
          <button className="link" onClick={() => supabase.auth.signOut()}>
            Se déconnecter
          </button>
        </div>
      </header>

      {showForm && (
        <form className="card form-inline" onSubmit={handleCreate}>
          <label>
            Nom du projet
            <input
              value={name}
              onChange={(e) => setName(e.target.value)}
              placeholder="Certification ISO 9001 — 2026"
              required
            />
          </label>
          <label>
            Norme visée
            <select value={standardCode} onChange={(e) => setStandardCode(e.target.value)} required>
              {standards.map((s) => (
                <option key={s.code} value={s.code}>
                  {s.name}
                </option>
              ))}
            </select>
          </label>
          <div className="norm-search">
            <p className="encart-description">
              Votre norme n'est pas dans la liste ? Indiquez-la : l'IA effectue la recherche
              approfondie et prépare immédiatement le schéma complet de votre dossier.
            </p>
            <div className="norm-search-row">
              <input
                value={normQuery}
                onChange={(e) => setNormQuery(e.target.value)}
                placeholder="Ex. ISO 13485, ISO 22000, ISO 50001…"
                disabled={generating}
              />
              <button
                type="button"
                onClick={handleGenerateStandard}
                disabled={generating || !normQuery.trim()}
              >
                {generating ? "Préparation en cours…" : "Préparer cette norme"}
              </button>
            </div>
            {generatingStep && <p className="encart-description">{generatingStep}</p>}
            {generateNotice && <p className="notice">{generateNotice}</p>}
          </div>
          {error && <p className="error">{error}</p>}
          <button type="submit" disabled={loading || generating}>
            {loading ? "Création…" : "Créer le projet"}
          </button>
        </form>
      )}

      {projects.length === 0 && !showForm && (
        <div className="card empty-state">
          <p>
            Vous n'avez pas encore de projet. Créez votre premier projet de certification : la
            plateforme vous indiquera précisément les documents à fournir.
          </p>
        </div>
      )}

      <div className="project-list">
        {projects.map((p) => (
          <Link to={`/projets/${p.id}`} key={p.id} className="card project-card">
            <h2>{p.name}</h2>
            <span className={`badge badge-${p.status}`}>{STATUS_LABELS[p.status] ?? p.status}</span>
          </Link>
        ))}
      </div>
    </div>
  );
}
