import { useEffect, useState, FormEvent } from "react";
import { Link } from "react-router-dom";
import { supabase } from "../lib/supabase";
import { apiPost } from "../lib/api";
import { useAuth } from "../contexts/AuthContext";

interface Project {
  id: string;
  name: string;
  status: string;
  created_at: string;
}

interface Standard {
  code: string;
  name: string;
}

const STATUS_LABELS: Record<string, string> = {
  en_cours: "En cours",
  audit: "Audit",
  correction: "Correction",
  finalise: "Finalisé",
};

interface GenerateStandardResult {
  existing: boolean;
  code: string;
  name: string;
  clausesCount?: number;
  documentsCount?: number;
  autoGenerated?: boolean;
}

export default function DashboardPage() {
  const { isPlatformAdmin } = useAuth();
  const [projects, setProjects] = useState<Project[]>([]);
  const [standards, setStandards] = useState<Standard[]>([]);
  const [showForm, setShowForm] = useState(false);
  const [name, setName] = useState("");
  const [standardCode, setStandardCode] = useState("");
  const [error, setError] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);
  const [normQuery, setNormQuery] = useState("");
  const [generating, setGenerating] = useState(false);
  const [generateNotice, setGenerateNotice] = useState<string | null>(null);

  async function loadData() {
    const [{ data: projectsData }, { data: standardsData }] = await Promise.all([
      supabase.from("projects").select("id, name, status, created_at").order("created_at", { ascending: false }),
      supabase.from("standards").select("code, name").eq("is_active", true),
    ]);
    setProjects(projectsData ?? []);
    setStandards(standardsData ?? []);
    if (standardsData?.length && !standardCode) setStandardCode(standardsData[0].code);
  }

  useEffect(() => {
    void loadData();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  async function handleGenerateStandard() {
    const query = normQuery.trim();
    if (!query || generating) return;
    setGenerating(true);
    setError(null);
    setGenerateNotice(null);

    let done = false;
    const startedAt = Date.now();

    const finishSuccess = async (result: GenerateStandardResult) => {
      if (done) return;
      done = true;
      await loadData();
      setStandardCode(result.code);
      setNormQuery("");
      setGenerateNotice(
        result.existing
          ? `${result.name} est déjà au catalogue — elle est sélectionnée ci-dessus.`
          : `${result.name} est prête` +
            (result.clausesCount
              ? ` (${result.clausesCount} clauses, ${result.documentsCount} documents requis)`
              : "") +
            `. Ce référentiel a été préparé automatiquement par l'IA ; un expert le relira prochainement. ` +
            `Vous pouvez dès maintenant créer votre projet.`
      );
      setGenerating(false);
    };

    const finishError = (message: string) => {
      if (done) return;
      done = true;
      setError(message);
      setGenerating(false);
    };

    // La génération peut durer plusieurs minutes : on lance l'appel, et en parallèle
    // on suit l'état de la demande en base. Le premier des deux qui conclut gagne.
    let fetchErrorMessage: string | null = null;
    apiPost<GenerateStandardResult>("/api/standards/generate", { query })
      .then((result) => void finishSuccess(result))
      .catch((err) => {
        fetchErrorMessage = err instanceof Error ? err.message : "La préparation a échoué";
      });

    const poll = window.setInterval(async () => {
      if (done) {
        window.clearInterval(poll);
        return;
      }
      const { data: request } = await supabase
        .from("standard_requests")
        .select("status, error_message, created_at, standards(code, name)")
        .eq("query", query)
        .order("created_at", { ascending: false })
        .limit(1)
        .maybeSingle();

      const fresh = request && new Date(request.created_at).getTime() > startedAt - 60000;
      if (fresh && request.status === "traitee" && request.standards) {
        window.clearInterval(poll);
        const std = request.standards as unknown as { code: string; name: string };
        await finishSuccess({ existing: false, code: std.code, name: std.name });
      } else if (fresh && request.status === "erreur") {
        window.clearInterval(poll);
        finishError(request.error_message || "La préparation a échoué");
      } else if (fetchErrorMessage && !fresh) {
        // L'appel a échoué et aucune demande n'a été créée : erreur immédiate (ex. norme non reconnue)
        window.clearInterval(poll);
        finishError(fetchErrorMessage);
      } else if (Date.now() - startedAt > 13 * 60 * 1000) {
        window.clearInterval(poll);
        finishError("La préparation prend plus de temps que prévu. Rechargez la page dans quelques minutes : la norme apparaîtra dans la liste.");
      }
    }, 8000);
  }

  async function handleCreate(e: FormEvent) {
    e.preventDefault();
    setError(null);
    setLoading(true);
    try {
      await apiPost("/api/projects/create", { name, standardCode });
      setName("");
      setShowForm(false);
      await loadData();
    } catch (err) {
      setError(err instanceof Error ? err.message : "Une erreur est survenue");
    } finally {
      setLoading(false);
    }
  }

  return (
    <div className="page">
      <header className="page-header">
        <h1>Vos projets de certification</h1>
        <div className="header-actions">
          {isPlatformAdmin && (
            <Link to="/admin" className="back-link">
              Administration
            </Link>
          )}
          <button onClick={() => setShowForm(!showForm)}>
            {showForm ? "Annuler" : "Nouveau projet"}
          </button>
          <button className="link" onClick={() => supabase.auth.signOut()}>
            Se déconnecter
          </button>
        </div>
      </header>

      {showForm && (
        <form className="card form-inline" onSubmit={handleCreate}>
          <label>
            Nom du projet
            <input
              value={name}
              onChange={(e) => setName(e.target.value)}
              placeholder="Certification ISO 9001 — 2026"
              required
            />
          </label>
          <label>
            Norme visée
            <select value={standardCode} onChange={(e) => setStandardCode(e.target.value)} required>
              {standards.map((s) => (
                <option key={s.code} value={s.code}>
                  {s.name}
                </option>
              ))}
            </select>
          </label>
          <div className="norm-search">
            <p className="encart-description">
              Votre norme n'est pas dans la liste ? Indiquez-la : l'IA effectue la recherche
              approfondie et prépare immédiatement le schéma complet de votre dossier.
            </p>
            <div className="norm-search-row">
              <input
                value={normQuery}
                onChange={(e) => setNormQuery(e.target.value)}
                placeholder="Ex. ISO 13485, ISO 22000, ISO 50001…"
                disabled={generating}
              />
              <button
                type="button"
                onClick={handleGenerateStandard}
                disabled={generating || !normQuery.trim()}
              >
                {generating ? "Recherche et préparation en cours… (1 à 3 min)" : "Préparer cette norme"}
              </button>
            </div>
            {generateNotice && <p className="notice">{generateNotice}</p>}
          </div>
          {error && <p className="error">{error}</p>}
          <button type="submit" disabled={loading || generating}>
            {loading ? "Création…" : "Créer le projet"}
          </button>
        </form>
      )}

      {projects.length === 0 && !showForm && (
        <div className="card empty-state">
          <p>
            Vous n'avez pas encore de projet. Créez votre premier projet de certification : la
            plateforme vous indiquera précisément les documents à fournir.
          </p>
        </div>
      )}

      <div className="project-list">
        {projects.map((p) => (
          <Link to={`/projets/${p.id}`} key={p.id} className="card project-card">
            <h2>{p.name}</h2>
            <span className={`badge badge-${p.status}`}>{STATUS_LABELS[p.status] ?? p.status}</span>
          </Link>
        ))}
      </div>
    </div>
  );
}
