import { useEffect, useState, FormEvent } from "react";
import { Link } from "react-router-dom";
import { supabase } from "../lib/supabase";
import { apiPost } from "../lib/api";
import { useAuth } from "../contexts/AuthContext";

interface Project {
  id: string;
  name: string;
  status: string;
  created_at: string;
}

interface Standard {
  code: string;
  name: string;
}

const STATUS_LABELS: Record<string, string> = {
  en_cours: "En cours",
  audit: "Audit",
  correction: "Correction",
  finalise: "Finalisé",
};

interface GenerateStandardResult {
  existing: boolean;
  code: string;
  name: string;
  clausesCount?: number;
  documentsCount?: number;
  autoGenerated?: boolean;
}

export default function DashboardPage() {
  const { isPlatformAdmin } = useAuth();
  const [projects, setProjects] = useState<Project[]>([]);
  const [standards, setStandards] = useState<Standard[]>([]);
  const [showForm, setShowForm] = useState(false);
  const [name, setName] = useState("");
  const [standardCode, setStandardCode] = useState("");
  const [error, setError] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);
  const [normQuery, setNormQuery] = useState("");
  const [generating, setGenerating] = useState(false);
  const [generateNotice, setGenerateNotice] = useState<string | null>(null);

  async function loadData() {
    const [{ data: projectsData }, { data: standardsData }] = await Promise.all([
      supabase.from("projects").select("id, name, status, created_at").order("created_at", { ascending: false }),
      supabase.from("standards").select("code, name").eq("is_active", true),
    ]);
    setProjects(projectsData ?? []);
    setStandards(standardsData ?? []);
    if (standardsData?.length && !standardCode) setStandardCode(standardsData[0].code);
  }

  useEffect(() => {
    void loadData();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  async function handleGenerateStandard() {
    if (!normQuery.trim() || generating) return;
    setGenerating(true);
    setError(null);
    setGenerateNotice(null);
    try {
      const result = await apiPost<GenerateStandardResult>("/api/standards/generate", {
        query: normQuery.trim(),
      });
      await loadData();
      setStandardCode(result.code);
      setNormQuery("");
      setGenerateNotice(
        result.existing
          ? `${result.name} est déjà au catalogue — elle est sélectionnée ci-dessus.`
          : `${result.name} est prête (${result.clausesCount} clauses, ${result.documentsCount} documents requis). ` +
            `Ce référentiel a été préparé automatiquement par l'IA ; un expert le relira prochainement. ` +
            `Vous pouvez dès maintenant créer votre projet.`
      );
    } catch (err) {
      setError(err instanceof Error ? err.message : "La préparation de la norme a échoué");
    } finally {
      setGenerating(false);
    }
  }

  async function handleCreate(e: FormEvent) {
    e.preventDefault();
    setError(null);
    setLoading(true);
    try {
      await apiPost("/api/projects/create", { name, standardCode });
      setName("");
      setShowForm(false);
      await loadData();
    } catch (err) {
      setError(err instanceof Error ? err.message : "Une erreur est survenue");
    } finally {
      setLoading(false);
    }
  }

  return (
    <div className="page">
      <header className="page-header">
        <h1>Vos projets de certification</h1>
        <div className="header-actions">
          {isPlatformAdmin && (
            <Link to="/admin" className="back-link">
              Administration
            </Link>
          )}
          <button onClick={() => setShowForm(!showForm)}>
            {showForm ? "Annuler" : "Nouveau projet"}
          </button>
          <button className="link" onClick={() => supabase.auth.signOut()}>
            Se déconnecter
          </button>
        </div>
      </header>

      {showForm && (
        <form className="card form-inline" onSubmit={handleCreate}>
          <label>
            Nom du projet
            <input
              value={name}
              onChange={(e) => setName(e.target.value)}
              placeholder="Certification ISO 9001 — 2026"
              required
            />
          </label>
          <label>
            Norme visée
            <select value={standardCode} onChange={(e) => setStandardCode(e.target.value)} required>
              {standards.map((s) => (
                <option key={s.code} value={s.code}>
                  {s.name}
                </option>
              ))}
            </select>
          </label>
          <div className="norm-search">
            <p className="encart-description">
              Votre norme n'est pas dans la liste ? Indiquez-la : l'IA effectue la recherche
              approfondie et prépare immédiatement le schéma complet de votre dossier.
            </p>
            <div className="norm-search-row">
              <input
                value={normQuery}
                onChange={(e) => setNormQuery(e.target.value)}
                placeholder="Ex. ISO 13485, ISO 22000, ISO 50001…"
                disabled={generating}
              />
              <button
                type="button"
                onClick={handleGenerateStandard}
                disabled={generating || !normQuery.trim()}
              >
                {generating ? "Recherche et préparation en cours… (1 à 3 min)" : "Préparer cette norme"}
              </button>
            </div>
            {generateNotice && <p className="notice">{generateNotice}</p>}
          </div>
          {error && <p className="error">{error}</p>}
          <button type="submit" disabled={loading || generating}>
            {loading ? "Création…" : "Créer le projet"}
          </button>
        </form>
      )}

      {projects.length === 0 && !showForm && (
        <div className="card empty-state">
          <p>
            Vous n'avez pas encore de projet. Créez votre premier projet de certification : la
            plateforme vous indiquera précisément les documents à fournir.
          </p>
        </div>
      )}

      <div className="project-list">
        {projects.map((p) => (
          <Link to={`/projets/${p.id}`} key={p.id} className="card project-card">
            <h2>{p.name}</h2>
            <span className={`badge badge-${p.status}`}>{STATUS_LABELS[p.status] ?? p.status}</span>
          </Link>
        ))}
      </div>
    </div>
  );
}
